num = int(input('Digite um número para ver o resultado:'))
#Tabuada de vezes de 1 a 9
print('-'*15)
print('Tabuada de vezes')
print('{} × {:2} = {}' .format(num, 1, num*1))
print('{} × {:2} = {}' .format(num, 2, num*2))
print('{} × {} = {}' .format(num, 3, num*3))
print('{} × {} = {}' .format(num, 4, num*4))
print('{} × {} = {}' .format(num, 5, num*5))
print('{} × {} = {}' .format(num, 6, num*6))
print('{} × {} = {}' .format(num, 7, num*7))
print('{} × {} = {}' .format(num, 8, num*8))
print('{} × {} = {}' .format(num, 9, num*9))
#Tabuada de adição de 1 a 9
print('-'*15)
print('Tabuada de adição')
print('{} + {} = {}' .format(num, 1, num+1))
print('{} + {} = {}' .format(num, 2, num+2))
print('{} + {} = {}' .format(num, 3, num+3))
print('{} + {} = {}' .format(num, 4, num+4))
print('{} + {} = {}' .format(num, 5, num+5))
print('{} + {} = {}' .format(num, 6, num+6))
print('{} + {} = {}' .format(num, 7, num+7))
print('{} + {} = {}' .format(num, 8, num+8))
print('{} + {} = {}' .format(num, 9, num+9))
#Tabuada de subtração de 1 a 9
print('-' *15)
print('Tabuada de subtração')
print('{} - {} = {}' .format(num, 1, num-1))
print('{} - {} = {}' .format(num, 2, num-2))
print('{} - {} = {}' .format(num, 3, num-3))
print('{} - {} = {}' .format(num, 4, num-4))
print('{} - {} = {}' .format(num, 5, num-5))
print('{} - {} = {}' .format(num, 6, num-6))
print('{} - {} = {}' .format(num, 7, num-7))
print('{} - {} = {}' .format(num, 8, num-8))
print('{} - {} = {}' .format(num, 9, num-9))
#Tabuada de divisão de 1 a 9
print('-' *15)
print('Tabuada de divisão')
print('{} / {} = {}' .format(num, 1, num/1))
print('{} / {} = {}' .format(num, 2, num/2))
print('{} / {} = {}' .format(num, 3, num/3))
print('{} / {} = {}' .format(num, 4, num/4))
print('{} / {} = {}' .format(num, 5, num/5))
print('{} / {} = {}' .format(num, 6, num/6))
print('{} / {} = {}' .format(num, 7, num/7))
print('{} / {} = {}' .format(num, 8, num/8))
print('{} / {} = {}' .format(num, 9, num/9))
#Tabuada de potênciação de 1 a 9
print('-' *15)
print('Tabuada de potênciação')
print('{} ** {} = {}' .format(num, 1, num**1))
print('{} ** {} = {}' .format(num, 2, num**2))
print('{} ** {} = {}' .format(num, 3, num**3))
print('{} ** {} = {}' .format(num, 4, num**4))
print('{} ** {} = {}' .format(num, 5, num**5))
print('{} ** {} = {}' .format(num, 6, num**6))
print('{} ** {} = {}' .format(num, 7, num**7))
print('{} ** {} = {}' .format(num, 8, num**8))
print('{} ** {} = {}' .format(num, 9, num**9))
#Tabuada de divisão inteira de 1 a 9
print('-' *15)
print('Tabuada de divisão')
print('{} // {} = {}' .format(num, 1, num//1))
print('{} // {} = {}' .format(num, 2, num//2))
print('{} // {} = {}' .format(num, 3, num//3))
print('{} // {} = {}' .format(num, 4, num//4))
print('{} // {} = {}' .format(num, 5, num//5))
print('{} // {} = {}' .format(num, 6, num//6))
print('{} // {} = {}' .format(num, 7, num//7))
print('{} // {} = {}' .format(num, 8, num//8))
print('{} // {} = {}' .format(num, 9, num//9))
print('-' *25)
print('Me siga no instagam @geecko___')
print('-' *25)